#ifndef FPGA_SOLVER_H
#define FPGA_SOLVER_H

#include <limits>

#include <iostream>
#include <string.h>

#include <ap_int.h>
#include <hls_stream.h>
#include <math.h>
#include <utils/x_hls_utils.h>
#include <ap_axi_sdata.h>


//REQUIRES FPGA BITSTREAM RECOMPILE
#define _FPGA_MAX_LITERALS (8192*4)
#define _FPGA_MAX_CLAUSES 131072
#define _FPGA_MAX_TREE_HEIGHT 32
#define _FPGA_MAX_LBD_BUCKETS 10
#define _FPGA_CLS_STATES_PARTITION 8
#define _FPGA_CLS_STATES_SELECT_BITS 4
#define _FPGA_DISC_LMD_DEP_DIST 5
#define _FPGA_CLS_DEP_DIST 5
#define _FPGA_RESOLVE_DEP_DIST 3
#define _FPGA_PARALLEL_MINIMIZE 2
#define _FPGA_MAX_LEARN_ELE 1024
#define _FPGA_MAX_LEARN_ELE_BITS 10

//REQUIRES FPGA BITSTREAM RECOMPILE
//MUST BE MULTIPLE OF 16
#define _FPGA_MAX_LITERAL_ELEMENTS (256*4096)
#define _HOST_MAX_LITERAL_ELEMENTS _FPGA_MAX_LITERAL_ELEMENTS
#define _HOST_MAX_CLAUSE_ELEMENTS _HOST_MAX_LITERAL_ELEMENTS

//FOR THE CONFIGURATION.JSON FILE:

//MUST START AT 16 FOR ALIGNMENT OF 512 BITS
//MUST BE MULTIPLE OF 16
//_HOST_LITERAL_PAGE_SIZE 16

//FOR STORING CLAUSES, MUST START AT 4 FOR ALIGNMENT OF 128 BYTES
//MUST BE MULTIPLE OF 4
// _HOST_CLAUSE_PAGE_SIZE 4

//DECIDE AS POSITIVE OR NEGATIVE
// _HOST_POSITIVE_LIT_PHASE_VAL false

//MULTIPLIER USED TO DECAY VSIDS
// _HOST_DECAY_FACTOR 0.95

//PRUNE PERCENTAGE AFTER RESET
// _HOST_PRUNE_PERCENTRAGE 0.1

//RESET MULTIPLIER
// _HOST_RESET_MULTIPLIER 100

const int MAX_STREAM_DEPTH=(_FPGA_MAX_LITERALS/4);
const unsigned int _MAX_PAGES_LIT_STORE_=_FPGA_MAX_LITERAL_ELEMENTS/16;
const unsigned int _MAX_PAGES_CLS_STORE_=_FPGA_MAX_LITERAL_ELEMENTS/4;

extern int spentRemoving;
extern int overhead;
extern int splitResidualCnt;
extern unsigned int checkCnt;

void sendTime(hls::stream<ap_axiu<64,0,0,0>>& timerValueStream, hls::stream<ap_axiu<1,0,0,0>>& conditionStream, 
    const unsigned int code, volatile uint64_t* store);
#endif